baseURL = 'https://shorinbonsai.github.io/'
languageCode = 'en-us'
title = 'The Junction'
enableEmoji = true
theme = "anatole"

[params]
title = "The Junction"
author = "James Sargant"
description = "A Digital Home"
profilePicture = "images/profile_pic.jpeg"
mainSections = ["blog"]
displayMode = "dark"
contentratio = 0.6


[[params.socialIcons]]
icon = "fab fa-linkedin"
title = "LinkedIn"
url = "https://www.linkedin.com/in/james-sargant-75b84ba7/"

[[params.socialIcons]]
icon = "fab fa-github"
title = "GitHub"
url = "https://github.com/shorinbonsai"


[[params.socialIcons]]
icon = "fas fa-envelope"
title = "e-mail"
url = "mailto:shorinbonsai@gmail.com"




[menu]

  [[menu.main]]
  name = "Home"
  identifier = "home"
  weight = 100
  url = "/"

  [[menu.main]]
  name = "Blog"
  weight = 200
  identifier = "blog"
  url = "/blog/"

  [[menu.main]]
  name = "Portfolio"
  weight = 300
  identifier = "portfolio"
  url = "/portfolio/"